# 修改后不会对已有的界碑生效
name:
  line: 1
  prefix: '#'
  suffix: '#'

# 修改后不会对已有的界碑生效
marker_id:
  line: 2
  prefix: 'No.'
  suffix: '*'

max_marks_per_district: 10

# 是否将区域渲染到BlueMap插件
blue_map: false

debug: false